[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.single"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
healthcheckInterval = 10
healthcheckConsecutiveFailures = 5
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"

