[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.single"

[deploy]
healthcheckPath = "/api/config"
healthcheckTimeout = 100
restartPolicyType = "always"
healthcheckInterval = 10
healthcheckConsecutiveFailures = 5

